// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_visits.sql

package db

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*)::bigint FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisits)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, ip, user_agent, referer, status, created_at
`

type CreateLinkVisitParams struct {
	LinkID    int64  `json:"link_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	Referer   string `json:"referer"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listLinkVisitsPage = `-- name: ListLinkVisitsPage :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListLinkVisitsPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinkVisitsPage(ctx context.Context, arg ListLinkVisitsPageParams) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listLinkVisitsPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkVisit{}
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
