// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*)::bigint FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name)
VALUES ($1, $2)
RETURNING id, original_url, short_name, created_at
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE short_name = $1
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const listLinksPage = `-- name: ListLinksPage :many
SELECT id, original_url, short_name, created_at
FROM links
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListLinksPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinksPage(ctx context.Context, arg ListLinksPageParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = $2, short_name = $3
WHERE id = $1
RETURNING id, original_url, short_name, created_at
`

type UpdateLinkParams struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}
