// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortName   string             `json:"short_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LinkVisit struct {
	ID        int64              `json:"id"`
	LinkID    int64              `json:"link_id"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
	Referer   string             `json:"referer"`
	Status    int32              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
